### PR TITLE
fix dependency issue

### PR DESCRIPTION
**Pull request by EranXu**
## Issue
* [Jira Issue Link](https://siyangzhang.atlassian.net/jira/software/projects/TTG/boards/2/backlog?selectedIssue=TTG-68)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test Cases (adds test cases to the implementation PR)
- [ ] This change requires a documentation update

## Description
* solve dependency issues in package.json
* Use `npm ci --legacy-peer-deps` instead of `npm install` because CI stands for clean install to install all exact version dependencies or devDependencies from a package-lock

## Reference Links
* https://stackoverflow.com/questions/71713111/mui-installation-doesnt-work-with-react-18
* https://docs.npmjs.com/cli/v9/commands/npm-ci

### CODE REVIEW

**Review by AlexYoungZ — APPROVED** [review]
lgtm

**Comment by dishant9397** [comment]
@EranXu We are using `npm install --legacy-peer-deps` and I was wondering if we can try to solve dependency issue without using `legacy-peer-deps` flag.

**Comment by EranXu** [comment]
> 
@dishant9397 
No this is the known issue between mui v5 and react 18 and this is the common fix for that. There’s no fix but only workarounds.

**Comment by dishant9397** [comment]
> > 
> 
> @dishant9397 No this is the known issue between mui v5 and react 18 and this is the common fix for that. There’s no fix but only workarounds.

I guess we can than close this PR because I have already added flag in netlify and also added instruction in the README.md so should be fine.

**Pull request closed without merging**
